### ISSUE TITLE
User Registration:

### ISSUE THREAD

**Issue by BeccAllfor1** [BeccAllfor1/FlavaSava-recipe-site#1]
As a new user, I want to register an account, so that I can access and contribute to the recipe sharing site.
-Acceptance criteria 1: User can fill out a registration form with username, email, and password.
-Acceptance criteria 2: User receives a confirmation email to verify their account.
https://github.com/BeccAllfor1/FlavaSava-recipe-site.git

**Comment by hamid-kordi** [comment]
hello 
It helps if you do it yourself
If you think you don't have the patience to do it, you must look for the source
 You can use the following repository
It has everything you want.

https://github.com/amirbigg/django-social-network

**Comment by BeccAllfor1** [comment]
Thank you, I have no problem with doing the registration, I did it last week but using aullauth, however we will be deciding who does it as a team but thank you for the code it will be useful as we have all only been lea for 1 week now.Sent from my iPhoneOn Jun 25, 2024, at 6:43 PM, hamidreza kordi ***@***.***> wrote:﻿
hello
It helps if you do it yourself
If you think you don't have the patience to do it, you must look for the source
You can use the following repository
It has everything you want.
https://github.com/amirbigg/django-social-network
